branches:
  only:
    - master
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

jdk: openjdk8

language: scala

scala: 2.12.10

# Cleanup the cached directories to avoid unnecessary cache updates
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# These directories are cached to a cloud storage provider "close" to the infrastructure the builds run on.
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt



jobs:
  include:
    - stage: lint
      script: sbt ++$TRAVIS_SCALA_VERSION! check

    - &build-test
      stage: build & test
      jdk: openjdk11
      scala: 2.13.1
      script:
        - set -e -o pipefail
        - docker-compose up -d
        - sbt ++$TRAVIS_SCALA_VERSION! coverage test coverageReport coverageAggregate

    - <<: *build-test
      jdk: openjdk8
      scala: 2.13.1

    - <<: *build-test
      jdk: openjdk11
      scala: 2.12.10

    - <<: *build-test
      jdk: openjdk11
      scala: 2.12.10

    - stage: release
      if: tag IS present
      script:
        - set -e -o pipefail
        - git fetch --tags
        - echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$SONATYPE_USER\", \"$SONATYPE_PASSWORD\")" > ~/.sbt/1.0/sonatype.sbt
        - echo "$PGP_PUBLIC" > /tmp/public.asc
        - echo "$PGP_SECRET" > /tmp/secret.asc
        - sbt ++$TRAVIS_SCALA_VERSION! clean sonatypeBundleClean +publishSigned sonatypeBundleRelease